name: Slack Notification Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send_review:
    uses: ./.github/workflows/slack-alert.yml
    with:
      reviewer: "Danny Torrence"
      property_name: "Overlook Hotel"
      rating: "1.0"
      review_text: "Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."

